/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'materials',
        title: 'Materials',
        type: 'basic',
        icon: 'heroicons_outline:chart-pie',
        link: '/materials',
        permissions: ['admin', 'staff'],
    },
    {
        id: 'accounts',
        title: 'Accounts',
        type: 'basic',
        icon: 'heroicons_outline:user',
        link: '/accounts',
    },
    {
        id: 'departments',
        title: 'Departments',
        type: 'basic',
        icon: 'heroicons_outline:server-stack',
        link: '/departments',
    },
    {
        id: 'categories',
        title: 'Categories',
        type: 'basic',
        icon: 'heroicons_outline:inbox-stack',
        link: '/categories',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:cube',
        link: '/products',
    },
    {
        id: 'Production Plans',
        title: 'Production Plans',
        type: 'basic',
        icon: 'heroicons_outline:rectangle-stack',
        link: '/production-plans',
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'materials',
        title: 'Materials',
        type: 'basic',
        icon: 'heroicons_outline:chart-pie',
        link: '/materials',
    },
    {
        id: 'accounts',
        title: 'Accounts',
        type: 'basic',
        icon: 'heroicons_outline:user',
        link: '/accounts',
    },
    {
        id: 'departments',
        title: 'Departments',
        type: 'basic',
        icon: 'heroicons_outline:server-stack',
        link: '/departments',
    },
    {
        id: 'categories',
        title: 'Categories',
        type: 'basic',
        icon: 'heroicons_outline:inbox-stack',
        link: '/categories',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:cube',
        link: '/products',
    },
    {
        id: 'production-plans',
        title: 'Production Plans',
        type: 'basic',
        icon: 'heroicons_outline:rectangle-stack',
        link: '/production-plans',
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'materials',
        title: 'Materials',
        type: 'basic',
        icon: 'heroicons_outline:chart-pie',
        link: '/materials',
    },
    {
        id: 'accounts',
        title: 'Accounts',
        type: 'basic',
        icon: 'heroicons_outline:user',
        link: '/accounts',
    },
    {
        id: 'departments',
        title: 'Departments',
        type: 'basic',
        icon: 'heroicons_outline:server-stack',
        link: '/departments',
    },
    {
        id: 'categories',
        title: 'Categories',
        type: 'basic',
        icon: 'heroicons_outline:inbox-stack',
        link: '/categories',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:cube',
        link: '/products',
    },
    {
        id: 'production-plans',
        title: 'Production Plans',
        type: 'basic',
        icon: 'heroicons_outline:rectangle-stack',
        link: '/production-plans',
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'materials',
        title: 'Materials',
        type: 'basic',
        icon: 'heroicons_outline:chart-pie',
        link: '/materials',
    },
    {
        id: 'accounts',
        title: 'Accounts',
        type: 'basic',
        icon: 'heroicons_outline:users',
        link: '/accounts',
    },
    {
        id: 'departments',
        title: 'Departments',
        type: 'basic',
        icon: 'heroicons_outline:server-stack',
        link: '/departments',
    },
    {
        id: 'categories',
        title: 'Categories',
        type: 'basic',
        icon: 'heroicons_outline:inbox-stack',
        link: '/categories',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:cube',
        link: '/products',
    },
    {
        id: 'production-plans',
        title: 'Production Plans',
        type: 'basic',
        icon: 'heroicons_outline:rectangle-stack',
        link: '/production-plans',
    },
];
