export const data = {
    material: {
        inputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '54db7e98-9a54-456f-4f43-08dcbac4b03f',
                quantity: 20,
                consumption: 50,
                isProduct: false,
                type: 0,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
        outputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '0fffc30f-cbb3-4119-4f44-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'b3b987f7-5ec1-4025-4f45-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
    },
    product: {
        inputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '54db7e98-9a54-456f-4f43-08dcbac4b03f',
                quantity: 20,
                consumption: 50,
                isProduct: false,
                type: 0,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
        outputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '0fffc30f-cbb3-4119-4f44-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'b3b987f7-5ec1-4025-4f45-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
    },
    semi: {
        inputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '54db7e98-9a54-456f-4f43-08dcbac4b03f',
                quantity: 20,
                consumption: 50,
                isProduct: false,
                type: 0,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
        outputs: [
            {
                name: 'name ne',
                code: 'NameNe01',
                id: '0fffc30f-cbb3-4119-4f44-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'b3b987f7-5ec1-4025-4f45-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
            {
                name: 'name ne',
                code: 'NameNe01',
                id: 'edcb3434-101b-4a68-4f46-08dcbac4b03f',
                quantity: 30,
                consumption: 20,
                isProduct: false,
                type: 1,
                totalQuantity: 100,
                totalConsumption: 200,
            },
        ],
    },
};
